stages:
  - registry
  - testing

registry:
  stage: registry
  image: docker
  services:
    - name: docker:dind
      command: [ "--insecure-registry=registry.hal.davecutting.uk"]
  script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  - docker build -t $CI_REGISTRY_IMAGE .
  - docker push $CI_REGISTRY_IMAGE
  tags: [dockerindocker]

unit testing:
  stage: testing
  image: gradle:7.2.0-jdk17
  script:
    - ./gradlew test --tests UnitTests   

integration testing:
  stage: testing
  image: gradle:7.2.0-jdk17
  script:
    - ./gradlew test --tests IntegrationTests   